// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxolgsepghoyemnjbual.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4b2xnc2VwZ2hveWVtbmpidWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTM1NTMsImV4cCI6MjA2Njc4OTU1M30.jB1WAWjPhAWwSkuW4QSsFeltdQ7OCeWkzwepgwuqoMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);